/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import model.Project;

public class App {

    public static void main(String[] args) {
        Project p = new Project();
       
        p.setName("Novo projeto");
        p.setDescription("projeto test");
        ProjectController controller = new ProjectController();
        
        controller.save(p);
    }
}
